//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtProyectoDavid
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductoEnCarrito
    {
        [ScaffoldColumn(false)]
        public int pcr_id { get; set; }
        [ScaffoldColumn(false)]
        public int car_id { get; set; }
        [ScaffoldColumn(false)]
        public int prd_id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El estado es requerido"), MaxLength(50)]
        [Display(Name = "Estado")]
        public string pcr_est { get; set; }
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        [Required(ErrorMessage = "El cantidad es requerida")]
        [Display(Name = "Cantidad")]
        public Nullable<int> prd_cnt { get; set; }
        public Nullable<System.DateTime> pcr_dateOfCreated { get; set; }
        
        public virtual Carrito Carrito { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
