//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtProyectoDavid
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Promocion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promocion()
        {
            this.Producto = new HashSet<Producto>();
        }
        [ScaffoldColumn(false)]
        public int prm_id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los Nombres son requerido"), MaxLength(50)]
        [Display(Name = "Nombres")]
        public string prm_nom { get; set; }
        
        [Required(ErrorMessage = "El tipo de Promoción es requerido")]
        [Display(Name = "Tipo")]
        public bool prm_tip { get; set; }

        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        [Required(ErrorMessage = "El Número es requerido")]
        [Display(Name = "Cantidad")]
        public int prm_can { get; set; }


        [Range(2, 10, ErrorMessage = "El porcentaje debe ser entre 0 y 100")]
        [Required(ErrorMessage = "El Porcentaje es requerido")]
        [Display(Name = "Porcentaje de Descuento")]
        public byte prm_por { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
