//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtProyectoDavid
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
        }
        [ScaffoldColumn(false)]
        public int uso_id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los Usuario es requerido"), MaxLength(30)]
        [Display(Name = "Usuario")]
        public string uso_usu { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "La contraseña es requerida"), MaxLength(30)]
        [Display(Name = "Contraseña")]
        public string uso_con { get; set; }
        [ScaffoldColumn(false)]
        public string uso_rol { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los Nombres son requerido"), MaxLength(60)]
        [Display(Name = "Nombres")]
        public string uso_nom { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El correo es requerido"), MaxLength(50)]
        [Display(Name = "Correo")]
        public string uso_cor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
